apiVersion: v1
kind: Service
metadata:
  name: svc-safc
spec:
  type: NodePort
  ipFamilyPolicy: PreferDualStack
  selector:
    app: ticket
    club: safc
  ports:
    - port: 9001
      targetPort: 80
      nodePort: 31111
